### ISSUE TITLE
The package only works with R >= 4.0.0

### ISSUE THREAD

**Issue by Wytzepakito** [data-cleaning/dcmodifydb#6]
I tested with version 3.6.2, 4.0.0 and 4.1.2. The package uses bquote with the argument spice = TRUE in alter_stmt, this was added in R version 4.0.0. [R changelog](https://cran.r-project.org/doc/manuals/r-release/NEWS.html)

**Comment by edwindj** [comment]
Not sure if we should strive for backwards compatability: especially because since dbplyr and dplyr also changed a lot.

Suggestion: added R >- 4.0.0. to DESCRIPTION

**Comment by Wytzepakito** [comment]
I'm also unsure about that, but I agree with your suggestion!
